CREATE DATABASE IF NOT EXISTS api;
USE api;

CREATE TABLE api_user (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE api_security (
    id INT AUTO_INCREMENT PRIMARY KEY,
    jwt_secret VARCHAR(255) NOT NULL,
    jwt_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);